export const EducationPrompts = [
  'An interactive history lesson on the Roman Empire with augmented reality.',
  'A 3D model of the solar system for a science project.',
  'A virtual field trip to the Great Wall of China for students.',
  'An AI-powered tutor for math and science subjects.',
  'A digital library with access to thousands of educational books and resources.',
  'A coding challenge to teach programming concepts.',
  'A quiz app for testing knowledge on famous historical figures.',
  'A language learning app with interactive lessons.',
  'A virtual science lab for conducting experiments.',
  'A storytelling app to encourage creative writing in children.',
  'A platform for connecting students with online tutors.',
  'A geography game to learn world capitals and landmarks.',
  'An app for practicing musical instruments and learning to read sheet music.',
  'A virtual chemistry set for safe and interactive chemistry experiments.',
  'A history timeline visualization tool for better understanding historical events.',
  'A platform for teachers to create and share lesson plans.',
  'An app for learning coding and computer programming.',
  'A math problem solver with step-by-step explanations.',
  'A virtual art studio for practicing drawing and painting.',
  'A tool for learning and practicing foreign languages with native speakers.',
  'An app for studying and preparing for standardized tests.',
  'A virtual classroom for remote learning and collaboration.',
  'A platform for teaching and learning about environmental conservation.',
  'An interactive anatomy tool for studying the human body.',
  'A tool for learning about space and astronomy.',
  'A physics simulator for understanding physical concepts.',
  'An app for learning about famous works of literature and authors.',
  'A platform for exploring and understanding world cultures and traditions.',
  'An app for learning about endangered species and conservation efforts.',
  'A virtual tour of famous art museums and galleries.',
  'A geography quiz game to test knowledge of world geography.',
  'An app for learning about historical events and timelines.',
  'A math game for improving math skills in a fun way.',
  'A virtual debate platform for practicing critical thinking and public speaking.',
  'A platform for learning about the history of different civilizations.',
  'An app for exploring the wonders of the natural world.',
  'A tool for understanding and solving complex physics problems.',
  'A virtual chemistry lab for safe and engaging chemistry experiments.',
  'An app for exploring the lives of famous scientists and inventors.',
  'A language translation tool for learning new languages.',
  'A platform for learning about the history and culture of indigenous peoples.',
  'An app for learning about famous landmarks and historical sites.',
  'A tool for studying and understanding the principles of economics.',
  'A virtual music school for learning to play musical instruments and compose music.',
];
